---
language: android
jdk: oraclejdk8
sudo: false
os: linux
dist: trusty

branches:
  only:
    - master
    - dev
    - feature/setup-github-actions

env:
  global:
    - ANDROID_TARGET=android-30
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - android-30
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-25
    - sys-img-armeabi-v7a-android-27
    - sys-img-armeabi-v7a-android-29

licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - 'android-sdk-preview-license-.+'

script:
  - ./gradlew runUnitTests
  - ./gradlew connectedCheck

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
