---
language: android
jdk: oraclejdk11
sudo: required
os: linux
dist: trusty

branches:
  only:
    - master
    - dev
    - feature/setup-github-actions

env:
  global:
    - ANDROID_TARGET=android-30
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    - sys-img-${ANDROID_ABI}-android-21
    - sys-img-${ANDROID_ABI}-android-23
    - sys-img-${ANDROID_ABI}-android-25
    - sys-img-${ANDROID_ABI}-android-27
    - sys-img-${ANDROID_ABI}-android-29

licenses:
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'
  - 'android-sdk-preview-license-.+'

before_install:
  - yes | sdkmanager --update
  - yes | sdkmanager "platforms;android-30"

script:
  - ./gradlew runUnitTests
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
