---
language: android
jdk: openjdk11
sudo: true
os: linux
dist: trusty

branches:
  only:
    - master
    - dev
    - feature/setup-github-actions

env:
  global:
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - platform-tools
    - build-tools-30.0.2
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-${ANDROID_ABI}-android-21
    - sys-img-${ANDROID_ABI}-android-22
    - sys-img-${ANDROID_ABI}-android-25
    - sys-img-${ANDROID_ABI}-android-27
    - sys-img-${ANDROID_ABI}-android-29

before_install:
  - yes | sdkmanager --licenses
  - yes | sdkmanager "platforms;android-30"

script:
  - ./gradlew runUnitTests
  - ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
